### ISSUE TITLE
Cannot build minimalInstall branch with the instructions from the Readme

### ISSUE THREAD

**Issue by AlexanderFabisch** [envire/buildconf#6]
Autoproj seems to have some trouble with an empty overrides.yml:

```
$ aup
operating system: ubuntu,debian - 16.04,16.04.2,lts,xenial,xerus
updating autoproj                                               
bundler: connected to https://rubygems.org/
updated autoproj main configuration         

no implicit conversion of nil into Array
```

Commenting all lines in the overrides.yml seems to fix this problem.

**Comment by Rauldg** [comment]
Looks like an autoproj error.

**Comment by planthaber** [comment]
Well not empty, but an empty overrides Array in the yml:
https://github.com/rock-core/autoproj/issues/137

this was introduced with autoproj 2

**Comment by AlexanderFabisch** [comment]
OK, after fixing this issue, I have another one. Seems like PCL 1.8 is not built correctly:

```
envire/envire_pcl(/home/dfki.uni-bremen.de/afabisch/tmp/envire/envire/envire_pcl): failed in configure phase
    'cmake -DCMAKE_INSTALL_PREFIX=/home/dfki.uni-bremen.de/afabisch/tmp/envire/install -DCMAKE_MODULE_PATH= -DCMAKE_PREFIX_PATH=/home/dfki.uni-bremen.de/afabisch/tmp/envire/install -DROCK_TEST_ENABLED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DROCK_TEST_LOG_DIR=/home/dfki.uni-bremen.de/afabisch/tmp/envire/envire/envire_pcl/build/test/results -DROCK_USE_CXX11=TRUE -DCMAKE_CXX_FLAGS=  -std=c++11 -DCMAKE_BUILD_TYPE=RelWithDebInfo /home/dfki.uni-bremen.de/afabisch/tmp/envire/envire/envire_pcl' returned status 1
    see /home/dfki.uni-bremen.de/afabisch/tmp/envire/install/log/envire/envire_pcl-configure.log for details
    last 10 lines are:

      with requested version "1.8".
    
      The following configuration files were considered but not accepted:
    
        /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake, version: 1.7.2
    
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/dfki.uni-bremen.de/afabisch/tmp/envire/envire/envire_pcl/build/CMakeFiles/CMakeOutput.log".
```

**Comment by AlexanderFabisch** [comment]
Three packages are complaining about this error:
* envire_pcl
* envire_visualizer
* envire/tutorials

I talked with Arne and I try to fix it now

**Comment by planthaber** [comment]
> With requested version "1.8". [...] PCLConfig.cmake, version: 1.7.2

I think i know whats wrong... you should upgrade your PCL version.

**Comment by AlexanderFabisch** [comment]
There are several problems:
* The rock package set tries to install pcl from the system. in Entern this is overridden with `Autoproj.add_osdeps_overrides 'slam/pcl', :force => true`.
* The override for the pcl version does not seem to work. I checked out the branch pcl-1.8.0 manually, made an aup and the branch has not been changed. So this manual fix works for me.
* PCL does not build, I have to set a symbolic link manually: `sudo ln -s /usr/lib/x86_64-linux-gnu/libproj.so.9 /usr/lib/x86_64-linux-gnu/libproj.so`

Now PCL seems to be compiling...

**Comment by AlexanderFabisch** [comment]
OK, it works but the PCL installation is a mess. Anyone who knows how this is done in the Entern buildconf should fix this here. I have no clue.

**Comment by Rauldg** [comment]
I found a couple of commits related to this and now it builds.

In overrides.rb the line:

`Autoproj.add_osdeps_overrides 'slam/pcl', :force => true`

Force using package slam/pcl even if it is provided as osdep.
This is required for switching to pcl 1.8 on Ubuntu 16.04

And the line 
`Autobuild::Package['slam/pcl'].define "WITH_VTK", "FALSE"`

was introduced by @planthaber not sure what it is for. Maybe we don't need this one.

This is the commit which incorporates these commands:

https://github.com/envire/buildconf/commit/ffb2e071d97826b2c0e02587018b1959fe064d9d

**Comment by planthaber** [comment]
> Autobuild::Package['slam/pcl'].define "WITH_VTK", "FALSE"

As far as I remember the ubuntus vtk package is linked to QT5, where rock used QT4, which resulted in crashes in some programs using both

**Comment by AlexanderFabisch** [comment]
I can confirm that it works now, even on a fresh docker container. :)
